# Generated by Django 5.0.6 on 2024-06-07 23:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('isbn', models.IntegerField(unique=True, validators=[django.core.validators.MinValueValidator(1000000000000), django.core.validators.MaxValueValidator(9999999999999)])),
                ('book_name', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=30)),
                ('publisher', models.CharField(max_length=15)),
                ('languages', models.CharField(choices=[('ES', 'Español'), ('EN', 'Inglés')], max_length=20)),
                ('description', models.TextField(max_length=1500)),
                ('image', models.ImageField(upload_to='books')),
                ('category', models.CharField(choices=[('34', 'Poesía'), ('37', 'Religión'), ('5', 'Fantasía'), ('8', 'Romance'), ('12', 'Historia'), ('9', 'Terror'), ('21', 'Política'), ('3', 'Aventura'), ('26', 'Música'), ('2', 'No Ficción'), ('22', 'Sociología'), ('31', 'Deportes'), ('6', 'Misterio'), ('27', 'Teatro'), ('24', 'Educación'), ('35', 'Ensayo'), ('36', 'Crítica Literaria'), ('38', 'Espiritualidad'), ('39', 'Juvenil'), ('18', 'Autoayuda'), ('1', 'Ficción'), ('28', 'Cine'), ('33', 'Cómics'), ('13', 'Filosofía'), ('14', 'Ciencia'), ('23', 'Psicología'), ('7', 'Thriller'), ('4', 'Ciencia Ficción'), ('40', 'Infantil'), ('25', 'Arte'), ('29', 'Cocina'), ('19', 'Negocios'), ('32', 'Juegos'), ('16', 'Matemáticas'), ('30', 'Viajes'), ('11', 'Autobiografía'), ('17', 'Salud'), ('15', 'Tecnología'), ('10', 'Biografía'), ('20', 'Economía')], max_length=20)),
                ('sub_category', models.CharField(blank=True, choices=[('34', 'Poesía'), ('37', 'Religión'), ('5', 'Fantasía'), ('8', 'Romance'), ('12', 'Historia'), ('9', 'Terror'), ('21', 'Política'), ('3', 'Aventura'), ('26', 'Música'), ('2', 'No Ficción'), ('22', 'Sociología'), ('31', 'Deportes'), ('6', 'Misterio'), ('27', 'Teatro'), ('24', 'Educación'), ('35', 'Ensayo'), ('36', 'Crítica Literaria'), ('38', 'Espiritualidad'), ('39', 'Juvenil'), ('18', 'Autoayuda'), ('1', 'Ficción'), ('28', 'Cine'), ('33', 'Cómics'), ('13', 'Filosofía'), ('14', 'Ciencia'), ('23', 'Psicología'), ('7', 'Thriller'), ('4', 'Ciencia Ficción'), ('40', 'Infantil'), ('25', 'Arte'), ('29', 'Cocina'), ('19', 'Negocios'), ('32', 'Juegos'), ('16', 'Matemáticas'), ('30', 'Viajes'), ('11', 'Autobiografía'), ('17', 'Salud'), ('15', 'Tecnología'), ('10', 'Biografía'), ('20', 'Economía')], max_length=20, null=True)),
                ('is_new', models.BooleanField(default=True)),
                ('on_sale', models.BooleanField(default=False)),
                ('publish', models.BooleanField(default=False)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
