# Generated by Django 5.0.6 on 2024-06-05 21:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('isbn', models.IntegerField(unique=True, validators=[django.core.validators.MinValueValidator(1000000000000), django.core.validators.MaxValueValidator(9999999999999)])),
                ('book_name', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=30)),
                ('publisher', models.CharField(max_length=15)),
                ('languages', models.CharField(choices=[('EN', 'Inglés'), ('ES', 'Español')], max_length=20)),
                ('description', models.TextField(max_length=1500)),
                ('image', models.ImageField(upload_to='dashboard_app/media/books')),
                ('category', models.CharField(choices=[('20', 'Economía'), ('10', 'Biografía'), ('4', 'Ciencia Ficción'), ('26', 'Música'), ('16', 'Matemáticas'), ('31', 'Deportes'), ('15', 'Tecnología'), ('1', 'Ficción'), ('25', 'Arte'), ('17', 'Salud'), ('33', 'Cómics'), ('13', 'Filosofía'), ('18', 'Autoayuda'), ('35', 'Ensayo'), ('24', 'Educación'), ('2', 'No Ficción'), ('34', 'Poesía'), ('30', 'Viajes'), ('6', 'Misterio'), ('3', 'Aventura'), ('19', 'Negocios'), ('11', 'Autobiografía'), ('22', 'Sociología'), ('37', 'Religión'), ('7', 'Thriller'), ('12', 'Historia'), ('21', 'Política'), ('40', 'Infantil'), ('5', 'Fantasía'), ('36 Literaria', 'Crítica Literaria'), ('9', 'Terror'), ('28', 'Cine'), ('8', 'Romance'), ('38', 'Espiritualidad'), ('27', 'Teatro'), ('14', 'Ciencia'), ('32', 'Juegos'), ('29', 'Cocina'), ('23', 'Psicología'), ('39', 'Juvenil')], max_length=20)),
                ('sub_category', models.CharField(blank=True, choices=[('20', 'Economía'), ('10', 'Biografía'), ('4', 'Ciencia Ficción'), ('26', 'Música'), ('16', 'Matemáticas'), ('31', 'Deportes'), ('15', 'Tecnología'), ('1', 'Ficción'), ('25', 'Arte'), ('17', 'Salud'), ('33', 'Cómics'), ('13', 'Filosofía'), ('18', 'Autoayuda'), ('35', 'Ensayo'), ('24', 'Educación'), ('2', 'No Ficción'), ('34', 'Poesía'), ('30', 'Viajes'), ('6', 'Misterio'), ('3', 'Aventura'), ('19', 'Negocios'), ('11', 'Autobiografía'), ('22', 'Sociología'), ('37', 'Religión'), ('7', 'Thriller'), ('12', 'Historia'), ('21', 'Política'), ('40', 'Infantil'), ('5', 'Fantasía'), ('36 Literaria', 'Crítica Literaria'), ('9', 'Terror'), ('28', 'Cine'), ('8', 'Romance'), ('38', 'Espiritualidad'), ('27', 'Teatro'), ('14', 'Ciencia'), ('32', 'Juegos'), ('29', 'Cocina'), ('23', 'Psicología'), ('39', 'Juvenil')], max_length=20, null=True)),
                ('is_new', models.BooleanField(default=True)),
                ('on_sale', models.BooleanField(default=False)),
                ('publish', models.BooleanField(default=False)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='customuser',
            name='profile_img',
            field=models.ImageField(blank=True, upload_to='dashboard/media/users'),
        ),
    ]
