# Generated by Django 5.0.6 on 2024-06-08 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_app', '0002_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.CharField(choices=[('34', 'Poesía'), ('14', 'Ciencia'), ('10', 'Biografía'), ('3', 'Aventura'), ('18', 'Autoayuda'), ('33', 'Cómics'), ('7', 'Thriller'), ('9', 'Terror'), ('23', 'Psicología'), ('8', 'Romance'), ('17', 'Salud'), ('40', 'Infantil'), ('36', 'Crítica Literaria'), ('4', 'Ciencia Ficción'), ('21', 'Política'), ('19', 'Negocios'), ('32', 'Juegos'), ('6', 'Misterio'), ('15', 'Tecnología'), ('13', 'Filosofía'), ('29', 'Cocina'), ('37', 'Religión'), ('28', 'Cine'), ('22', 'Sociología'), ('30', 'Viajes'), ('1', 'Ficción'), ('35', 'Ensayo'), ('31', 'Deportes'), ('2', 'No Ficción'), ('27', 'Teatro'), ('20', 'Economía'), ('26', 'Música'), ('16', 'Matemáticas'), ('38', 'Espiritualidad'), ('25', 'Arte'), ('39', 'Juvenil'), ('5', 'Fantasía'), ('24', 'Educación'), ('11', 'Autobiografía'), ('12', 'Historia')], max_length=20),
        ),
        migrations.AlterField(
            model_name='book',
            name='languages',
            field=models.CharField(choices=[('EN', 'Inglés'), ('ES', 'Español')], max_length=20),
        ),
        migrations.AlterField(
            model_name='book',
            name='sub_category',
            field=models.CharField(blank=True, choices=[('34', 'Poesía'), ('14', 'Ciencia'), ('10', 'Biografía'), ('3', 'Aventura'), ('18', 'Autoayuda'), ('33', 'Cómics'), ('7', 'Thriller'), ('9', 'Terror'), ('23', 'Psicología'), ('8', 'Romance'), ('17', 'Salud'), ('40', 'Infantil'), ('36', 'Crítica Literaria'), ('4', 'Ciencia Ficción'), ('21', 'Política'), ('19', 'Negocios'), ('32', 'Juegos'), ('6', 'Misterio'), ('15', 'Tecnología'), ('13', 'Filosofía'), ('29', 'Cocina'), ('37', 'Religión'), ('28', 'Cine'), ('22', 'Sociología'), ('30', 'Viajes'), ('1', 'Ficción'), ('35', 'Ensayo'), ('31', 'Deportes'), ('2', 'No Ficción'), ('27', 'Teatro'), ('20', 'Economía'), ('26', 'Música'), ('16', 'Matemáticas'), ('38', 'Espiritualidad'), ('25', 'Arte'), ('39', 'Juvenil'), ('5', 'Fantasía'), ('24', 'Educación'), ('11', 'Autobiografía'), ('12', 'Historia')], max_length=20, null=True),
        ),
    ]
