# Generated by Django 5.0.6 on 2024-06-09 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_app', '0003_alter_book_category_alter_book_languages_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.CharField(choices=[('34', 'Poesía'), ('24', 'Educación'), ('17', 'Salud'), ('14', 'Ciencia'), ('19', 'Negocios'), ('12', 'Historia'), ('21', 'Política'), ('23', 'Psicología'), ('18', 'Autoayuda'), ('15', 'Tecnología'), ('10', 'Biografía'), ('26', 'Música'), ('13', 'Filosofía'), ('25', 'Arte'), ('4', 'Ciencia Ficción'), ('27', 'Teatro'), ('9', 'Terror'), ('35', 'Ensayo'), ('38', 'Espiritualidad'), ('7', 'Thriller'), ('36', 'Crítica Literaria'), ('16', 'Matemáticas'), ('6', 'Misterio'), ('11', 'Autobiografía'), ('39', 'Juvenil'), ('2', 'No Ficción'), ('29', 'Cocina'), ('1', 'Ficción'), ('31', 'Deportes'), ('40', 'Infantil'), ('32', 'Juegos'), ('20', 'Economía'), ('8', 'Romance'), ('5', 'Fantasía'), ('28', 'Cine'), ('30', 'Viajes'), ('33', 'Cómics'), ('3', 'Aventura'), ('37', 'Religión'), ('22', 'Sociología')], max_length=20),
        ),
        migrations.AlterField(
            model_name='book',
            name='languages',
            field=models.CharField(choices=[('ES', 'Español'), ('EN', 'Inglés')], max_length=20),
        ),
        migrations.AlterField(
            model_name='book',
            name='sub_category',
            field=models.CharField(blank=True, choices=[('34', 'Poesía'), ('24', 'Educación'), ('17', 'Salud'), ('14', 'Ciencia'), ('19', 'Negocios'), ('12', 'Historia'), ('21', 'Política'), ('23', 'Psicología'), ('18', 'Autoayuda'), ('15', 'Tecnología'), ('10', 'Biografía'), ('26', 'Música'), ('13', 'Filosofía'), ('25', 'Arte'), ('4', 'Ciencia Ficción'), ('27', 'Teatro'), ('9', 'Terror'), ('35', 'Ensayo'), ('38', 'Espiritualidad'), ('7', 'Thriller'), ('36', 'Crítica Literaria'), ('16', 'Matemáticas'), ('6', 'Misterio'), ('11', 'Autobiografía'), ('39', 'Juvenil'), ('2', 'No Ficción'), ('29', 'Cocina'), ('1', 'Ficción'), ('31', 'Deportes'), ('40', 'Infantil'), ('32', 'Juegos'), ('20', 'Economía'), ('8', 'Romance'), ('5', 'Fantasía'), ('28', 'Cine'), ('30', 'Viajes'), ('33', 'Cómics'), ('3', 'Aventura'), ('37', 'Religión'), ('22', 'Sociología')], max_length=20, null=True),
        ),
    ]
