# Generated by Django 5.0.6 on 2024-06-10 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_app', '0005_alter_book_category_alter_book_isbn_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.CharField(choices=[('32', 'Juegos'), ('6', 'Misterio'), ('33', 'Cómics'), ('39', 'Juvenil'), ('3', 'Aventura'), ('25', 'Arte'), ('28', 'Cine'), ('1', 'Ficción'), ('17', 'Salud'), ('35', 'Ensayo'), ('11', 'Autobiografía'), ('15', 'Tecnología'), ('24', 'Educación'), ('31', 'Deportes'), ('18', 'Autoayuda'), ('9', 'Terror'), ('4', 'Ciencia Ficción'), ('34', 'Poesía'), ('36', 'Crítica Literaria'), ('40', 'Infantil'), ('10', 'Biografía'), ('22', 'Sociología'), ('26', 'Música'), ('38', 'Espiritualidad'), ('7', 'Thriller'), ('14', 'Ciencia'), ('42', 'Suspenso'), ('20', 'Economía'), ('16', 'Matemáticas'), ('13', 'Filosofía'), ('2', 'No Ficción'), ('29', 'Cocina'), ('30', 'Viajes'), ('19', 'Negocios'), ('41', 'Novela'), ('23', 'Psicología'), ('12', 'Historia'), ('21', 'Política'), ('5', 'Fantasía'), ('8', 'Romance'), ('37', 'Religión'), ('27', 'Teatro')], max_length=20),
        ),
        migrations.AlterField(
            model_name='book',
            name='languages',
            field=models.CharField(choices=[('ES', 'Español'), ('EN', 'Inglés')], max_length=20),
        ),
        migrations.AlterField(
            model_name='book',
            name='sub_category',
            field=models.CharField(blank=True, choices=[('32', 'Juegos'), ('6', 'Misterio'), ('33', 'Cómics'), ('39', 'Juvenil'), ('3', 'Aventura'), ('25', 'Arte'), ('28', 'Cine'), ('1', 'Ficción'), ('17', 'Salud'), ('35', 'Ensayo'), ('11', 'Autobiografía'), ('15', 'Tecnología'), ('24', 'Educación'), ('31', 'Deportes'), ('18', 'Autoayuda'), ('9', 'Terror'), ('4', 'Ciencia Ficción'), ('34', 'Poesía'), ('36', 'Crítica Literaria'), ('40', 'Infantil'), ('10', 'Biografía'), ('22', 'Sociología'), ('26', 'Música'), ('38', 'Espiritualidad'), ('7', 'Thriller'), ('14', 'Ciencia'), ('42', 'Suspenso'), ('20', 'Economía'), ('16', 'Matemáticas'), ('13', 'Filosofía'), ('2', 'No Ficción'), ('29', 'Cocina'), ('30', 'Viajes'), ('19', 'Negocios'), ('41', 'Novela'), ('23', 'Psicología'), ('12', 'Historia'), ('21', 'Política'), ('5', 'Fantasía'), ('8', 'Romance'), ('37', 'Religión'), ('27', 'Teatro')], max_length=20, null=True),
        ),
    ]
