# Generated by Django 5.0.6 on 2024-06-30 06:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_app', '0006_alter_book_category_alter_book_languages_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.CharField(choices=[('30', 'Viajes'), ('19', 'Negocios'), ('11', 'Autobiografía'), ('39', 'Juvenil'), ('27', 'Teatro'), ('5', 'Fantasía'), ('10', 'Biografía'), ('1', 'Ficción'), ('37', 'Religión'), ('7', 'Thriller'), ('12', 'Historia'), ('16', 'Matemáticas'), ('29', 'Cocina'), ('35', 'Ensayo'), ('15', 'Tecnología'), ('38', 'Espiritualidad'), ('31', 'Deportes'), ('8', 'Romance'), ('40', 'Infantil'), ('33', 'Cómics'), ('25', 'Arte'), ('26', 'Música'), ('2', 'No Ficción'), ('36', 'Crítica Literaria'), ('13', 'Filosofía'), ('34', 'Poesía'), ('23', 'Psicología'), ('4', 'Ciencia Ficción'), ('32', 'Juegos'), ('9', 'Terror'), ('20', 'Economía'), ('3', 'Aventura'), ('18', 'Autoayuda'), ('24', 'Educación'), ('17', 'Salud'), ('14', 'Ciencia'), ('41', 'Novela'), ('42', 'Suspenso'), ('28', 'Cine'), ('21', 'Política'), ('22', 'Sociología'), ('6', 'Misterio')], max_length=20),
        ),
        migrations.AlterField(
            model_name='book',
            name='sub_category',
            field=models.CharField(blank=True, choices=[('30', 'Viajes'), ('19', 'Negocios'), ('11', 'Autobiografía'), ('39', 'Juvenil'), ('27', 'Teatro'), ('5', 'Fantasía'), ('10', 'Biografía'), ('1', 'Ficción'), ('37', 'Religión'), ('7', 'Thriller'), ('12', 'Historia'), ('16', 'Matemáticas'), ('29', 'Cocina'), ('35', 'Ensayo'), ('15', 'Tecnología'), ('38', 'Espiritualidad'), ('31', 'Deportes'), ('8', 'Romance'), ('40', 'Infantil'), ('33', 'Cómics'), ('25', 'Arte'), ('26', 'Música'), ('2', 'No Ficción'), ('36', 'Crítica Literaria'), ('13', 'Filosofía'), ('34', 'Poesía'), ('23', 'Psicología'), ('4', 'Ciencia Ficción'), ('32', 'Juegos'), ('9', 'Terror'), ('20', 'Economía'), ('3', 'Aventura'), ('18', 'Autoayuda'), ('24', 'Educación'), ('17', 'Salud'), ('14', 'Ciencia'), ('41', 'Novela'), ('42', 'Suspenso'), ('28', 'Cine'), ('21', 'Política'), ('22', 'Sociología'), ('6', 'Misterio')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(100000000), django.core.validators.MaxValueValidator(999999999)]),
        ),
    ]
