# Generated by Django 5.0.6 on 2024-07-01 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_app', '0008_alter_book_category_alter_book_sub_category_shopping_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopping',
            name='card',
        ),
    ]
