# Generated by Django 5.0.6 on 2024-07-01 06:02

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_app', '0009_remove_shopping_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopping',
            name='phone_number',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(100000000), django.core.validators.MaxValueValidator(999999999)]),
        ),
        migrations.AlterField(
            model_name='shopping',
            name='amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='shoppingitem',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard_app.book'),
        ),
    ]
