# Generated by Django 5.0.6 on 2024-07-01 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_app', '0010_shopping_phone_number_alter_shopping_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppingitem',
            name='price',
        ),
    ]
