# Generated by Django 5.0.6 on 2024-07-01 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_app', '0011_remove_shoppingitem_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopping',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
