# Generated by Django 5.0.6 on 2024-07-01 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_app', '0015_customuser_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='about',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
