# Generated by Django 5.0.6 on 2024-07-08 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_app', '0019_alter_book_book_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='publisher',
            field=models.CharField(max_length=30),
        ),
    ]
